name: Backup
on:
  schedule:
    - cron: "10 10 1-31/2 * *"
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check and release
        run: |
            rm -fr *
            sudo apt update
            sudo apt install upx git -y
            sudo snap install go --classic
            git clone -b master https://github.com/HyNetwork/hysteria hysteria-core> /dev/null
            cd hysteria-core/cmd
            GOOS=linux GOARCH=amd64 go build -trimpath -ldflags "-s -w -buildid=" -o ../../hysteria
            cd ../../
            upx --best hysteria
            #shopt -s extglob
            #rm -vrf !("hysteria")
            rm -rf hysteria-core
            mkdir -p .github/workflows
            wget -qO .github/workflows/Backup.yml https://github.com/${{ github.repository }}/raw/main/.github/workflows/Backup.yml &> /dev/null
            git config --global init.defaultBranch main
            git init
            git add .
            git config user.name "Scaleya"
            git config user.email "61817665+Scaleya@users.noreply.github.com"
            git commit -m "hysteria amd64 binary"
            git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push origin main --force
